apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "nexus-settlement.labels" . | nindent 4 }}
type: Opaque
stringData:
  host:     {{ .Values.secrets.postgres.host | quote }}
  port:     {{ .Values.secrets.postgres.port | quote }}
  db:       {{ .Values.secrets.postgres.db | quote }}
  user:     {{ .Values.secrets.postgres.user | quote }}
  password: {{ .Values.secrets.postgres.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "nexus-settlement.labels" . | nindent 4 }}
type: Opaque
stringData:
  url:      {{ .Values.secrets.redis.url | quote }}
  password: {{ .Values.secrets.redis.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "nexus-settlement.labels" . | nindent 4 }}
type: Opaque
stringData:
  public-key-base64: {{ .Values.secrets.jwt.publicKeyBase64 | quote }}
  algorithm:         {{ .Values.secrets.jwt.algorithm | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-secrets
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "nexus-settlement.labels" . | nindent 4 }}
type: Opaque
stringData:
  bootstrap-servers: {{ .Values.secrets.kafka.bootstrapServers | quote }}
